version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - pip install --upgrade pip
      - pip install -r requirements.txt
  build:
    commands:
      - echo Running training script...
      - python training_test.py
      - echo Uploading outputs to S3...
      - aws s3 cp output/ s3://aiml-project-artifact-taeyunryu/outputs/ --recursive
artifacts:
  files:
    - '**/*'      
  discard-paths: yes
  base-directory: . 
